labels:
  device: odin

steps:
  - name: uname
    image: alpine
    commands:
      - echo "Running test on Odin"
      - uname -a
    when:
      labels:
        linux: arm64
      event:
        - push