services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'   # Web UI
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
    env_file:
      - ../../env/nginxproxymanager.env

volumes:
  data:
  letsencrypt: